### ISSUE TITLE
Generate random non-assigned session ID

### ISSUE THREAD

**Issue by bryant-ta** [cs130-w21/20#21]
Generate random non-assigned session ID
Under Story #4

**Comment by elrodrigues** [comment]
Hey @khzheng24998, could you open a draft pull request with your changes? This is the last task left to close Story #4 and Epic #1

**Comment by khzheng24998** [comment]
> Hey @khzheng24998, could you open a draft pull request with your changes? This is the last task left to close Story #4 and Epic #1

@elrodrigues Done!
