### ISSUE TITLE
Algorithm Inputs and Outputs

### ISSUE THREAD

**Issue by elrodrigues** [cs130-w21/20#24]
Figure out inputs and outputs of algorithm. Crucial for #4 and #5

**Comment by bryant-ta** [comment]
Personality Traits and Portfolio Tilts Towards Value and Size. Andrew Conlin and Jouko Miettunen
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3018383

**Data Used**: Study data included the stocks held, number of shares owned, and value of each position at end-of-month over 2 year period

**Categories Used**: Based on Temperament and Character Inventory (TCI) of Cloninger et al. (1993). Using novelty seeking and reward dependence scales.
	• "We now briefly describe the subscales, starting with the novelty seeking subscales. Exploratory excitability measures one's willingness and desire to seek new things and avoid boredom. Impulsiveness measures the willingness to make decisions based on hunches and without having complete information. High scores on extravagance reflect a preference for spending money over saving money, even to the point of being careless. People scoring high on disorderliness are willing to do things their own way without much regard for routines or rules. The reward dependence subscale sentimentality measures our tendency to be affected by emotional stimuli, whether it be other people or works of art. People scoring high in attachment are generally warm and open with others. High scores on dependence reflect one's willingness and desire to fit into a social group."

**Conclusion**: 
       - Compared a person holding value vs. growth stocks and large capitalization vs. small capitalization stocks
		• More explorative-extravagant individuals --> hold large capitalization growth stocks
		• More impulsiveness-disorderliness --> small capitalization growth stocks
		• More sentimentality --> small capitalization value stocks
		• More social --> small capitalization value stocks.

**Related Info**:

What is growth vs. value stock? https://www.investopedia.com/articles/professionals/072415/value-or-growth-stocks-which-best.asp#:~:text=Growth%20stocks%20are%20those%20companies,thus%20provide%20a%20superior%20return.
Temperament and Character Inventory Scale (including in relation to Five Factor Model) https://en.wikipedia.org/wiki/Temperament_and_Character_Inventory

**Comment by elrodrigues** [comment]
Sorry for being late!

Behavioral Finance: A Study of Correlation Between Personality Traits with the Investment Patterns in the Stock Market
https://link.springer.com/chapter/10.1007/978-81-322-1979-8_11
[PDF download](https://github.com/cs130-w21/20/files/5960938/Rizvi-Fatima2015_Chapter_BehavioralFinanceAStudyOfCorre.pdf)

**Data Used**: Broad survey asking for general investment behavior and personal questions like age and number of dependents. The inputs here are not really relevant to our project

**Outputs**: The Five Factor Model: **Extroversion**, **Agreeableness**, **Conscientiousness**, **Neuroticism**, and **Openness to Experience**.

**Conclusion**: (from the paper) The study found a significant relationship between demographic profile of the investors and their investment in the stock market. There is a significant relationship between investment behavior and the Five Factor personality model.

**Comment by daniel77chen** [comment]
- ### The Impact of the Big Five Traits and Mood on Investment Performance – A Study of Individual Investors in Vietnam. (Trang Phung, Mai Khuong): https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2883425

**Data Used:** 255 responses from traders in the Veitnam stock market via survey

**Conclusion/Findings:** also based on the Big Five Personality Taxonomies 
-  Conscientiousness, Openness to experience, and Agreeableness have a direct effect on investment performance (though don't we can actually measure "performance")
-  Conscientiousness, Openness and Extraversion tend to cause people to be in a positive mood when trading 
- Agreeableness and Neuroticism tend to cause people to be a in negative mood when trading
 
- ### Examining the association between personality traits and stock market participation Evidence from Finnish university students (Hannes Jouhikainen): https://aaltodoc.aalto.fi/handle/123456789/432

**Data Used:** 771 responses from Finnish university students via questionnaire. 

**Conclusion/Findings:** also based on the Big Five Personality Taxonomies
- extraversion is positively associated with stock market participation
- agreeableness, neuroticism, and openness are negatively associated
