### ISSUE TITLE
Sprint 2 Tests, implement #33's TODO

### ISSUE THREAD

**Issue by elrodrigues** [cs130-w21/20#27]
Tests for sprint 2 components.
Depends on at least #21, #22, #23, and #24 

Implement #33's TODO: replace filler text with actual descriptions of personality outputs

Add Kenny's bug fix from #34

**Comment by elrodrigues** [comment]
Note: update travis.yml to run `flask init-db`

**Comment by daniel77chen** [comment]
Some definitions from the report we could use for descriptions of the personality output:

### **Exploratory Excitability" and Extravagance description:**
- **Exploratory excitability** refers to one's willingness and desire to seek new things and avoid boredom. **Extravagance** refers to one's preference for spending money over saving money. Thus, a higher score suggests you like new stimuli, spending money, and portfolios with more growth & large capitalization stocks.


### **Impulsiveness and Disorderliness description:**
- **Impulsiveness** refers to one's willingness to make decisions based on hunches and without necessarily having complete information. **Disorderliness** refers to one's willing to do things their own way without much regard for routines or rules. Thus, a higher score suggests you take risks, do not follow conventions, and have a portfolio with more growth & small capitalization stocks.

### **Attachment and Dependence description:**
- **Attachment** refers to one's tendency to be generally warm and open with others. **Dependence** refers to one's willingness and desire to fit into a social group. Thus, a higher score suggests you are more amicable, enjoy interacting with people, and have a portfolio with more small capitalization stocks. 

### **Sentimentality and Empathy description:**
- **Sentimentality** refers to one's tendency to be affected by emotional stimuli, whether it be other people or works of art. **Empathy** refers to one's ability to better understand and share the feelings of others. Thus, a higher score suggests you are more led by your emotions, understand the emotions of others, and have a portfolio with more value and small capitalization stocks.
