### ISSUE TITLE
Compare Algorithm

### ISSUE THREAD

**Issue by elrodrigues** [cs130-w21/20#36]
Under #9 
TODO: design compare algorithm

**Comment by bryant-ta** [comment]
@elrodrigues Do you know if Finnhub has an API call for stock sector? I can't seem to find one.

If they don't have one, I may need to use https://financialmodelingprep.com/developer/docs/#Company-Profile, but that is another API...

**Comment by elrodrigues** [comment]
> 
> 
> @elrodrigues Do you know if Finnhub has an API call for stock sector? I can't seem to find one.
> 
> If they don't have one, I may need to use https://financialmodelingprep.com/developer/docs/#Company-Profile for the interest/hobbies factor (if we are still considering that in compatibility), but that is another API...

Finnhub has the `finnhubIndustry` field here: https://finnhub.io/docs/api/company-profile2. I'm not sure if this is what you're looking for. I'll check out the API you linked.

**Comment by elrodrigues** [comment]
btw I think you pushed new changes to the `errands` branch. This branch was merged into master, so if you plan on working in `errands`, you may need a new pull request. I'm not sure how a pull request on a merged branch works though.

**Comment by bryant-ta** [comment]
Oh exactly what I was looking for, thanks. I'll go ahead and implement interests in the algorithm with that then.

For `errands`, I will make a new pull request once it's ready. I think I just need to sync `errands` with `master` beforehand.

**Comment by bryant-ta** [comment]
Tracking level of wealth as a factor in profile, using household wealth quintiles.

+/-15% compatibility scaled based on difference in quintile rank

U.S. Census Bureau 2021 report of median household wealth quintiles, Table:
https://www.thebalance.com/american-net-worth-by-state-metropolitan-4135839

---

+10% compatibility if both portfolios' most popular sector (by volume) matches

*Percentages subject to change
