### ISSUE TITLE
[BUG] - Sentimentality and Empathy calculation too sensitive

### ISSUE THREAD

**Issue by elrodrigues** [cs130-w21/20#46]
## Description
The calculation at line 90 of `algorithm.py` is too sensitive to large market-to-book ratios. With large stocks like MSFT, SENTIM is heavily skewed to 0%

## Steps to Reproduce
Steps to reproduce the bug:
- [x] Step 1: Add 20 MSFT shares
- [x] Step 2: Add 20 XELA shares
- [x] Step 3: Compute profile

## Expected Behavior
The algorithm should acknowledge small company stocks (XELA) when computed with large company stocks (MSFT)

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

**Comment by elrodrigues** [comment]
Proposed fix:

Change line 90 in `algorithm.py` to `person['SENTIM'] = floor(100/(1+exp(-S/30)))`

**Comment by khzheng24998** [comment]
@elrodrigues I just created a new PR for misc. improvements if you wanna add your changes for this bug fix without creating a new PR.

**Comment by elrodrigues** [comment]
Thanks Kenny
